{
  "status_code": "ERROR",
  "response": "HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /None/api/v1/edf/genai/codegenservices/from-sttm-generate-notebook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10231afb0>: Failed to establish a new connection: [Errno 61] Connection refused'))",
  "headers": {}
}